version: '3'
services:
  maria:
    image: mariadb:5.5.64
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "${ADMINER_PORT}:8080"
  httpd:
    image: httpd:2.4.39-alpine
    restart: on-failure
    volumes:
      - './apps/symfony/public:/usr/src/app'
      - './docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/httpd/server.key:/usr/local/apache2/conf/server.key:ro'
      - './docker/httpd/server.crt:/usr/local/apache2/conf/server.crt:ro'
      - './logs:/usr/local/apache2/logs'
    extra_hosts:
     - "chesscheat.local:127.0.0.1"
    hostname: chesscheat.local
    domainname: local
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    environment:
      COMPOSER_HOME: ${COMPOSER_HOME}
    volumes:
      - './apps/symfony:/usr/src/app'
    env_file:
      - .env
    user: ${LOCAL_USER}
